services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "${KAFKA_ADVERTISED_LISTENERS}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 104857600
      KAFKA_FETCH_MAX_BYTES: 104857600
      KAFKA_CREATE_TOPICS: >
        get.top.monthly.user:1:3,donor.user.validate:1:3,charity.user.validate:1:3,donor.validation.result:1:3,charity.validation.result:1:3,get.user.email:1:3,get.user.email.result:1:3,result.top.monthly.user:1:3
    depends_on:
      - zookeeper
    networks:
      - microservices
    volumes:
      - kafka-data:/var/lib/kafka

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    networks:
      - microservices
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: bigbang
    depends_on:
      - zookeeper

networks:
  microservices:
    external: true

volumes:
  zookeeper-data:
  kafka-data:
