import { HOST_URL, TEAM_A_HOST_URL } from "./AppUrlConfig";

const ANALYTICAL_SERVICE_URL = `${HOST_URL}/api`
const TEAM_A_ANALYTICAL_SERVICE_URL = `${TEAM_A_HOST_URL}/statistic`
const TEAM_A_PROJECT_SERVICE_URL = `${TEAM_A_HOST_URL}`


const TOTAL_DONATION = `${TEAM_A_ANALYTICAL_SERVICE_URL}/donation/total`
const PROJECT_COMPARISON = `${TEAM_A_ANALYTICAL_SERVICE_URL}/donation/compare`
const TOTAL_PROJECT_STATUS = `${TEAM_A_PROJECT_SERVICE_URL}/projects/total-status`
const GET_PROJECT_BY = `${TEAM_A_PROJECT_SERVICE_URL}/projects/total`
const PROJECT_DONATION_DONOR = `${ANALYTICAL_SERVICE_URL}/donors`
const PROJECT_DONATION_CHARITY = `${TEAM_A_ANALYTICAL_SERVICE_URL}/charity`
const DONOR_REGISTRATION = `${ANALYTICAL_SERVICE_URL}/users/registrations/Donor`

const GET_ALL_CATEGORIES = `${TEAM_A_PROJECT_SERVICE_URL}/category/all`
const GET_ALL_REGION = `${TEAM_A_PROJECT_SERVICE_URL}/region/all`

export default { ANALYTICAL_SERVICE_URL, GET_PROJECT_BY, PROJECT_COMPARISON, TOTAL_PROJECT_STATUS, TOTAL_DONATION, PROJECT_DONATION_DONOR, PROJECT_DONATION_CHARITY, DONOR_REGISTRATION, GET_ALL_CATEGORIES, GET_ALL_REGION }